version: '2.4'
services:
    server:
        build:
            context: .
        command: node ./dist/index.js
        container_name: 'server'
        env_file: .env.production
        depends_on:
            - database